require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UsersController do

  # This should return the minimal set of attributes required to create a valid
  # User. As you add validations to User, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UsersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  before(:each) do
    controller.stub(:authenticate_user!).and_return true
  end

  describe "GET index" do
    it "assigns all users as @users" do
      user = create(:user)
      get :index
      expect(assigns(:users)).to eq [user]
    end

    it "renders the :index template" do
      get :index
      expect(response).to render_template :index
    end
  end

  # describe "GET show" do
  #   it "assigns the requested user as @user" do
  #     user = create(:user)
  #     get :show, id: user
  #     assigns(:user).should eq(user)
  #   end
  #   it "renders the :show view" do
  #     user = create(:user)
  #     get :show, id: user
  #     expect(response).to render_template :show
  #   end
  # end

  describe "GET new" do
    it "assigns a new user as @user" do
      get :new
      expect(assigns(:user)).to be_a_new(User)
    end

    it "renders the :new template" do 
      get :new
      expect(response).to render_template :new
    end
  end

  describe "GET edit" do
    it "assigns the requested user as @user" do
      user = create(:user)
      get :edit, id: user
      expect(assigns(:user)).to eq(user)
    end
  end

  describe "POST create" do
    context "with valid params" do
      it "creates a new User" do
        expect {
          post :create, user: attributes_for(:user)
        }.to change(User, :count).by(1)
      end

      it "redirects to the created user" do
        post :create, user: attributes_for(:user)
        expect(response).to redirect_to(User.last)
      end
    end

    context "with invalid attributes" do
      it "does not save the new message in the database" do
        expect{
          post :create, user: attributes_for(:invalid_user)
        }.to_not change(User, :count)
      end
      
      it "re-renders the :new template" do 
        post :create, user: attributes_for(:invalid_user) 
        expect(response).to render_template :new
      end 
    end
  end

  describe "PUT update" do
    before :each do
      @user = create(:user)
    end

    it "locates the requested @user" do
      put :update, id: @user, user: attributes_for(:user)
      expect(assigns(:user)).to eq(@user)
    end

    context "with valid params" do
      it "updates the requested user" do
        put :update, id: @user, user: attributes_for(:user, display_name: "isaacnewton")
        @user.reload
        expect(@user.display_name).to eq("isaacnewton") 
      end

      it "redirects to the updated user" do
        put :update, id: @user, user: attributes_for(:user)
        expect(response).to redirect_to @user
      end
    end

    context "with invalid params" do
      it "does not update the requested user" do
        put :update, id: @user, user: attributes_for(:user, display_name: "isaacnewton", email: nil)
        @user.reload
        expect(@user.display_name).to_not eq("isaacnewton")
      end

      it "re-renders the :edit template" do
        put :update, id: @user, user: attributes_for(:invalid_user)
        expect(response).to render_template :edit
      end
    end
  end

  describe'DELETE destroy' do 
    before :each do
      @user = create(:user)
    end

    it "destroys the requested user" do 
      expect{
        delete :destroy, id: @user
      }.to change(User, :count).by(-1)
    end
    
    it "redirects to users#index" do 
      delete :destroy, id: @user 
      expect(response).to redirect_to users_url
    end
  end
end